name: named_page_view
description: >-
  Simple dependency that enable Page views to be controlled by enums, 
  simplifying the understanding and readability of the code.
version: '1.0.0'
homepage: https://github.com/gomon-dev/named_page_view

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true